export default {
  path: '/admin',
  component: () => import('@/layouts/AdminLayout.vue'),
  meta: { requiresAuth: true, requiresAdmin: true },
  children: [
    { path: '',                             name: 'admin.dashboard',              component: () => import('./dashboard/DashboardView.vue') },
    { path: 'products',                     name: 'admin.products',               component: () => import('./products/ProductsView.vue') },
    { path: 'products/create',              name: 'admin.products.create',        component: () => import('./products/ProductFormView.vue') },
    { path: 'products/:id/edit',            name: 'admin.products.edit',          component: () => import('./products/ProductFormView.vue') },
    { path: 'categories',                   name: 'admin.categories',             component: () => import('./categories/CategoriesView.vue') },
    { path: 'orders',                       name: 'admin.orders',                 component: () => import('./orders/OrdersView.vue') },
    { path: 'pos',                          name: 'admin.pos',                    component: () => import('./pos/PosView.vue') },
    { path: 'orders/:id',                   name: 'admin.order',                  component: () => import('./orders/OrderView.vue') },
    { path: 'coupons',                      name: 'admin.coupons',                component: () => import('./coupons/CouponsView.vue') },
    { path: 'users',                        name: 'admin.users',                  component: () => import('./users/UsersView.vue') },
    { path: 'settings',                     name: 'admin.settings',               component: () => import('./settings/SettingsView.vue') },
    { path: 'blog',                         name: 'admin.blog',                   component: () => import('./blog/BlogView.vue') },
    { path: 'blog/create',                  name: 'admin.blog.create',            component: () => import('./blog/BlogFormView.vue') },
    { path: 'blog/:id/edit',                name: 'admin.blog.edit',              component: () => import('./blog/BlogFormView.vue') },
    { path: 'product-lines',                name: 'admin.product-lines',          component: () => import('./product-lines/ProductLinesView.vue') },
    { path: 'product-lines/create',         name: 'admin.product-lines.create',   component: () => import('./product-lines/ProductLineFormView.vue') },
    { path: 'product-lines/:id/edit',       name: 'admin.product-lines.edit',     component: () => import('./product-lines/ProductLineFormView.vue') },
    { path: 'programme',                   name: 'admin.program',                component: () => import('./program/ProgramAdminView.vue') },
    { path: 'reviews',                     name: 'admin.reviews',                component: () => import('./reviews/ReviewsModerationView.vue') },
    { path: 'abandoned-carts',             name: 'admin.abandoned-carts',        component: () => import('./abandoned-carts/AbandonedCartsView.vue') },
    { path: 'newsletter',                  name: 'admin.newsletter',             component: () => import('./newsletter/NewsletterView.vue') },
    { path: 'deliveries',                  name: 'admin.deliveries',             component: () => import('./deliveries/DeliveriesView.vue') },
    { path: 'delivery-zones',              name: 'admin.delivery-zones',         component: () => import('./delivery-zones/DeliveryZonesView.vue') },
  ],
}
