export default {
  path: '/admin',
  component: () => import('@/layouts/AdminLayout.vue'),
  // requiresStaff : admin, manager ou agent staff. Le contrôle fin se fait
  // ensuite par `meta.permission` sur chaque route (voir router/index.js).
  meta: { requiresAuth: true, requiresStaff: true },
  children: [
    { path: '',                             name: 'admin.dashboard',              meta: { permission: 'dashboard.view' },       component: () => import('./dashboard/DashboardView.vue') },
    { path: 'products',                     name: 'admin.products',               meta: { permission: 'products.view' },        component: () => import('./products/ProductsView.vue') },
    { path: 'products/create',              name: 'admin.products.create',        meta: { permission: 'products.create' },      component: () => import('./products/ProductFormView.vue') },
    { path: 'products/:id/edit',            name: 'admin.products.edit',          meta: { permission: 'products.edit' },        component: () => import('./products/ProductFormView.vue') },
    { path: 'categories',                   name: 'admin.categories',             meta: { permission: 'categories.view' },      component: () => import('./categories/CategoriesView.vue') },
    { path: 'orders',                       name: 'admin.orders',                 meta: { permission: 'orders.view' },          component: () => import('./orders/OrdersView.vue') },
    { path: 'pos',                          name: 'admin.pos',                    meta: { permission: 'pos.use' },              component: () => import('./pos/PosView.vue') },
    { path: 'orders/:id',                   name: 'admin.order',                  meta: { permission: 'orders.view' },          component: () => import('./orders/OrderView.vue') },
    { path: 'coupons',                      name: 'admin.coupons',                meta: { permission: 'coupons.view' },         component: () => import('./coupons/CouponsView.vue') },
    { path: 'users',                        name: 'admin.users',                  meta: { permission: 'customers.view' },       component: () => import('./users/UsersView.vue') },
    { path: 'roles',                        name: 'admin.roles',                  meta: { permission: 'roles.view' },           component: () => import('./roles/RolesView.vue') },
    { path: 'permissions',                  name: 'admin.permissions',            meta: { permission: 'permissions.view' },     component: () => import('./permissions/PermissionsView.vue') },
    { path: 'settings',                     name: 'admin.settings',               meta: { permission: 'settings.view' },        component: () => import('./settings/SettingsView.vue') },
    { path: 'blog',                         name: 'admin.blog',                   meta: { permission: 'blog.view' },            component: () => import('./blog/BlogView.vue') },
    { path: 'blog/create',                  name: 'admin.blog.create',            meta: { permission: 'blog.create' },          component: () => import('./blog/BlogFormView.vue') },
    { path: 'blog/:id/edit',                name: 'admin.blog.edit',              meta: { permission: 'blog.edit' },            component: () => import('./blog/BlogFormView.vue') },
    { path: 'product-lines',                name: 'admin.product-lines',          meta: { permission: 'product_lines.view' },   component: () => import('./product-lines/ProductLinesView.vue') },
    { path: 'product-lines/create',         name: 'admin.product-lines.create',   meta: { permission: 'product_lines.create' }, component: () => import('./product-lines/ProductLineFormView.vue') },
    { path: 'product-lines/:id/edit',       name: 'admin.product-lines.edit',     meta: { permission: 'product_lines.edit' },   component: () => import('./product-lines/ProductLineFormView.vue') },
    { path: 'programme',                   name: 'admin.program',                meta: { permission: 'program.view' },         component: () => import('./program/ProgramAdminView.vue') },
    { path: 'reviews',                     name: 'admin.reviews',                meta: { permission: 'reviews.view' },         component: () => import('./reviews/ReviewsModerationView.vue') },
    { path: 'abandoned-carts',             name: 'admin.abandoned-carts',        meta: { permission: 'abandoned_carts.view' }, component: () => import('./abandoned-carts/AbandonedCartsView.vue') },
    { path: 'newsletter',                  name: 'admin.newsletter',             meta: { permission: 'newsletter.view' },      component: () => import('./newsletter/NewsletterView.vue') },
    { path: 'deliveries',                  name: 'admin.deliveries',             meta: { permission: 'deliveries.view' },      component: () => import('./deliveries/DeliveriesView.vue') },
    { path: 'delivery-zones',              name: 'admin.delivery-zones',         meta: { permission: 'delivery_zones.view' },  component: () => import('./delivery-zones/DeliveryZonesView.vue') },
  ],
}
